from setuptools import setup, find_packages

setup(name='tidyscreen',
      version='0.2.7',
      description='A library to manage data associated to drug screening campaigns',
      long_description=open('README.md').read().strip(),
      author="Alfredo Quevedo",
      author_email="aquevedo@unc.edu.ar",
      url='https://github.com/alfredoq/TidyScreen',
      license='GPLv3',
      python_requires='>=3.10',
      package_dir={'tidyscreen': 'src'},
      include_package_data=True,
      package_data={
          'tidyscreen.config': ['*.json'],
      },
      install_requires=[
        'pandas==2.2.1',
        'rdkit==2023.9.5',
        'openbabel-wheel',
        'pysqlite3',
        'termcolor',
	'pandarallel',
	'matplotlib',
	'joblib',
	'scipy',
	'loguru',
	'PyYAML',
	'tqdm',
	'multiprocess',
	'ringtail',
	'prody',
	'gemmi',
	'prolif',
	'moldf',
	'biobb_amber',
	'importlib_resources',
        'py3Dmol',
	'sqlite_web'
      ],
      packages=['tidyscreen', 'tidyscreen.chemspace', 'tidyscreen.config', 'tidyscreen.databases', 'tidyscreen.projects'],
      keywords='drug-discovery',
      classifiers=[
          "Programming Language :: Python :: 3.10",
          "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
          "Operating System :: OS Independent",
          "Topic :: virtual high-throughput screening",
      ],
      )
